{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_debug",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.2.aar",
          "url": "package_info_plus_debug-1.0.2.aar",
          "size": 7957,
          "sha512": "e64c2e1e3f50c629d3b1556e6233173484cc15a2b654942c62c8198fa93b486704ad51c533d9d2b691ff090aa85e200fa90f7a219e02d5f34548458ee6398b99",
          "sha256": "6d8d8ba4e357d5d1e9d80d957cd73eead33b9d5ae4cc870dcd1cea058d46c561",
          "sha1": "a56048320d9e781043c1dd32237e05c9f246b925",
          "md5": "8cf2bb8bd2aca1cd594355b0146a33c7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.2.aar",
          "url": "package_info_plus_debug-1.0.2.aar",
          "size": 7957,
          "sha512": "e64c2e1e3f50c629d3b1556e6233173484cc15a2b654942c62c8198fa93b486704ad51c533d9d2b691ff090aa85e200fa90f7a219e02d5f34548458ee6398b99",
          "sha256": "6d8d8ba4e357d5d1e9d80d957cd73eead33b9d5ae4cc870dcd1cea058d46c561",
          "sha1": "a56048320d9e781043c1dd32237e05c9f246b925",
          "md5": "8cf2bb8bd2aca1cd594355b0146a33c7"
        }
      ]
    }
  ]
}
