{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.packageinfo",
    "module": "package_info_plus_debug",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.1.aar",
          "url": "package_info_plus_debug-1.0.1.aar",
          "size": 7958,
          "sha512": "121980cfb00b0d121ab79f0ed331cac6e3232a7ab6f31a0156524cde2323b029ca16a02c696ddb15abef488371dbc05051d5c8d19efcbb9a1f962c7cf80b7006",
          "sha256": "616a054fb1faadb65aa7a35c3b065b84da6faf196bdd3874562ebe389e49496f",
          "sha1": "d3b7ff9725a935a3edeea8d051e3d85c30fc54b8",
          "md5": "5b37dcde8c76d98e2de2efcbb06acaa0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_debug-1.0.1.aar",
          "url": "package_info_plus_debug-1.0.1.aar",
          "size": 7958,
          "sha512": "121980cfb00b0d121ab79f0ed331cac6e3232a7ab6f31a0156524cde2323b029ca16a02c696ddb15abef488371dbc05051d5c8d19efcbb9a1f962c7cf80b7006",
          "sha256": "616a054fb1faadb65aa7a35c3b065b84da6faf196bdd3874562ebe389e49496f",
          "sha1": "d3b7ff9725a935a3edeea8d051e3d85c30fc54b8",
          "md5": "5b37dcde8c76d98e2de2efcbb06acaa0"
        }
      ]
    }
  ]
}
