// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: circuit_data_entity.proto

package technology.polygon.polygonid_protobuf;

public final class CircuitDataEntityOuterClass {
  private CircuitDataEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CircuitDataEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.CircuitDataEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string circuitId = 1;</code>
     * @return The circuitId.
     */
    String getCircuitId();
    /**
     * <code>string circuitId = 1;</code>
     * @return The bytes for circuitId.
     */
    com.google.protobuf.ByteString
        getCircuitIdBytes();

    /**
     * <code>bytes datFile = 2;</code>
     * @return The datFile.
     */
    com.google.protobuf.ByteString getDatFile();

    /**
     * <code>bytes zKeyFile = 3;</code>
     * @return The zKeyFile.
     */
    com.google.protobuf.ByteString getZKeyFile();
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.CircuitDataEntity}
   */
  public static final class CircuitDataEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.CircuitDataEntity)
      CircuitDataEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CircuitDataEntity.newBuilder() to construct.
    private CircuitDataEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CircuitDataEntity() {
      circuitId_ = "";
      datFile_ = com.google.protobuf.ByteString.EMPTY;
      zKeyFile_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new CircuitDataEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CircuitDataEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CircuitDataEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CircuitDataEntity.class, Builder.class);
    }

    public static final int CIRCUITID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object circuitId_ = "";
    /**
     * <code>string circuitId = 1;</code>
     * @return The circuitId.
     */
    @Override
    public String getCircuitId() {
      Object ref = circuitId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        circuitId_ = s;
        return s;
      }
    }
    /**
     * <code>string circuitId = 1;</code>
     * @return The bytes for circuitId.
     */
    @Override
    public com.google.protobuf.ByteString
        getCircuitIdBytes() {
      Object ref = circuitId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        circuitId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATFILE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString datFile_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes datFile = 2;</code>
     * @return The datFile.
     */
    @Override
    public com.google.protobuf.ByteString getDatFile() {
      return datFile_;
    }

    public static final int ZKEYFILE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString zKeyFile_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes zKeyFile = 3;</code>
     * @return The zKeyFile.
     */
    @Override
    public com.google.protobuf.ByteString getZKeyFile() {
      return zKeyFile_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(circuitId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, circuitId_);
      }
      if (!datFile_.isEmpty()) {
        output.writeBytes(2, datFile_);
      }
      if (!zKeyFile_.isEmpty()) {
        output.writeBytes(3, zKeyFile_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(circuitId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, circuitId_);
      }
      if (!datFile_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, datFile_);
      }
      if (!zKeyFile_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, zKeyFile_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof CircuitDataEntity)) {
        return super.equals(obj);
      }
      CircuitDataEntity other = (CircuitDataEntity) obj;

      if (!getCircuitId()
          .equals(other.getCircuitId())) return false;
      if (!getDatFile()
          .equals(other.getDatFile())) return false;
      if (!getZKeyFile()
          .equals(other.getZKeyFile())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CIRCUITID_FIELD_NUMBER;
      hash = (53 * hash) + getCircuitId().hashCode();
      hash = (37 * hash) + DATFILE_FIELD_NUMBER;
      hash = (53 * hash) + getDatFile().hashCode();
      hash = (37 * hash) + ZKEYFILE_FIELD_NUMBER;
      hash = (53 * hash) + getZKeyFile().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static CircuitDataEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CircuitDataEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CircuitDataEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CircuitDataEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CircuitDataEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static CircuitDataEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static CircuitDataEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CircuitDataEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static CircuitDataEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static CircuitDataEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static CircuitDataEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static CircuitDataEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(CircuitDataEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.CircuitDataEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.CircuitDataEntity)
        CircuitDataEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return CircuitDataEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return CircuitDataEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                CircuitDataEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.CircuitDataEntityOuterClass.CircuitDataEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        circuitId_ = "";
        datFile_ = com.google.protobuf.ByteString.EMPTY;
        zKeyFile_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return CircuitDataEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor;
      }

      @Override
      public CircuitDataEntity getDefaultInstanceForType() {
        return CircuitDataEntity.getDefaultInstance();
      }

      @Override
      public CircuitDataEntity build() {
        CircuitDataEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public CircuitDataEntity buildPartial() {
        CircuitDataEntity result = new CircuitDataEntity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(CircuitDataEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.circuitId_ = circuitId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.datFile_ = datFile_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.zKeyFile_ = zKeyFile_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof CircuitDataEntity) {
          return mergeFrom((CircuitDataEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(CircuitDataEntity other) {
        if (other == CircuitDataEntity.getDefaultInstance()) return this;
        if (!other.getCircuitId().isEmpty()) {
          circuitId_ = other.circuitId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDatFile() != com.google.protobuf.ByteString.EMPTY) {
          setDatFile(other.getDatFile());
        }
        if (other.getZKeyFile() != com.google.protobuf.ByteString.EMPTY) {
          setZKeyFile(other.getZKeyFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                circuitId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                datFile_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                zKeyFile_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object circuitId_ = "";
      /**
       * <code>string circuitId = 1;</code>
       * @return The circuitId.
       */
      public String getCircuitId() {
        Object ref = circuitId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          circuitId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string circuitId = 1;</code>
       * @return The bytes for circuitId.
       */
      public com.google.protobuf.ByteString
          getCircuitIdBytes() {
        Object ref = circuitId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          circuitId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string circuitId = 1;</code>
       * @param value The circuitId to set.
       * @return This builder for chaining.
       */
      public Builder setCircuitId(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        circuitId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string circuitId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCircuitId() {
        circuitId_ = getDefaultInstance().getCircuitId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string circuitId = 1;</code>
       * @param value The bytes for circuitId to set.
       * @return This builder for chaining.
       */
      public Builder setCircuitIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        circuitId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString datFile_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes datFile = 2;</code>
       * @return The datFile.
       */
      @Override
      public com.google.protobuf.ByteString getDatFile() {
        return datFile_;
      }
      /**
       * <code>bytes datFile = 2;</code>
       * @param value The datFile to set.
       * @return This builder for chaining.
       */
      public Builder setDatFile(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        datFile_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>bytes datFile = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatFile() {
        bitField0_ = (bitField0_ & ~0x00000002);
        datFile_ = getDefaultInstance().getDatFile();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString zKeyFile_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes zKeyFile = 3;</code>
       * @return The zKeyFile.
       */
      @Override
      public com.google.protobuf.ByteString getZKeyFile() {
        return zKeyFile_;
      }
      /**
       * <code>bytes zKeyFile = 3;</code>
       * @param value The zKeyFile to set.
       * @return This builder for chaining.
       */
      public Builder setZKeyFile(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        zKeyFile_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes zKeyFile = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearZKeyFile() {
        bitField0_ = (bitField0_ & ~0x00000004);
        zKeyFile_ = getDefaultInstance().getZKeyFile();
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.CircuitDataEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.CircuitDataEntity)
    private static final CircuitDataEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new CircuitDataEntity();
    }

    public static CircuitDataEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CircuitDataEntity>
        PARSER = new com.google.protobuf.AbstractParser<CircuitDataEntity>() {
      @Override
      public CircuitDataEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<CircuitDataEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<CircuitDataEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public CircuitDataEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\031circuit_data_entity.proto\022%technology." +
      "polygon.polygonid_protobuf\"I\n\021CircuitDat" +
      "aEntity\022\021\n\tcircuitId\030\001 \001(\t\022\017\n\007datFile\030\002 " +
      "\001(\014\022\020\n\010zKeyFile\030\003 \001(\014b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_CircuitDataEntity_descriptor,
        new String[] { "CircuitId", "DatFile", "ZKeyFile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
