// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: did_entity.proto

package technology.polygon.polygonid_protobuf;

public final class DidEntityOuterClass {
  private DidEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DidEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.DidEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    String getDid();
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    com.google.protobuf.ByteString
        getDidBytes();

    /**
     * <code>string identifier = 2;</code>
     * @return The identifier.
     */
    String getIdentifier();
    /**
     * <code>string identifier = 2;</code>
     * @return The bytes for identifier.
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <code>string blockchain = 3;</code>
     * @return The blockchain.
     */
    String getBlockchain();
    /**
     * <code>string blockchain = 3;</code>
     * @return The bytes for blockchain.
     */
    com.google.protobuf.ByteString
        getBlockchainBytes();

    /**
     * <code>string network = 4;</code>
     * @return The network.
     */
    String getNetwork();
    /**
     * <code>string network = 4;</code>
     * @return The bytes for network.
     */
    com.google.protobuf.ByteString
        getNetworkBytes();
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.DidEntity}
   */
  public static final class DidEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.DidEntity)
      DidEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DidEntity.newBuilder() to construct.
    private DidEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DidEntity() {
      did_ = "";
      identifier_ = "";
      blockchain_ = "";
      network_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new DidEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DidEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DidEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_DidEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DidEntity.class, Builder.class);
    }

    public static final int DID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object did_ = "";
    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    @Override
    public String getDid() {
      Object ref = did_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        did_ = s;
        return s;
      }
    }
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    @Override
    public com.google.protobuf.ByteString
        getDidBytes() {
      Object ref = did_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        did_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object identifier_ = "";
    /**
     * <code>string identifier = 2;</code>
     * @return The identifier.
     */
    @Override
    public String getIdentifier() {
      Object ref = identifier_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      }
    }
    /**
     * <code>string identifier = 2;</code>
     * @return The bytes for identifier.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      Object ref = identifier_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BLOCKCHAIN_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object blockchain_ = "";
    /**
     * <code>string blockchain = 3;</code>
     * @return The blockchain.
     */
    @Override
    public String getBlockchain() {
      Object ref = blockchain_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blockchain_ = s;
        return s;
      }
    }
    /**
     * <code>string blockchain = 3;</code>
     * @return The bytes for blockchain.
     */
    @Override
    public com.google.protobuf.ByteString
        getBlockchainBytes() {
      Object ref = blockchain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blockchain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object network_ = "";
    /**
     * <code>string network = 4;</code>
     * @return The network.
     */
    @Override
    public String getNetwork() {
      Object ref = network_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        network_ = s;
        return s;
      }
    }
    /**
     * <code>string network = 4;</code>
     * @return The bytes for network.
     */
    @Override
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, did_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identifier_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, identifier_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockchain_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, blockchain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, network_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, did_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(identifier_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, identifier_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockchain_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, blockchain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, network_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof DidEntity)) {
        return super.equals(obj);
      }
      DidEntity other = (DidEntity) obj;

      if (!getDid()
          .equals(other.getDid())) return false;
      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
      if (!getBlockchain()
          .equals(other.getBlockchain())) return false;
      if (!getNetwork()
          .equals(other.getNetwork())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DID_FIELD_NUMBER;
      hash = (53 * hash) + getDid().hashCode();
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
      hash = (37 * hash) + BLOCKCHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getBlockchain().hashCode();
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getNetwork().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static DidEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DidEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DidEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DidEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DidEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DidEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DidEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DidEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static DidEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static DidEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static DidEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static DidEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(DidEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.DidEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.DidEntity)
        DidEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DidEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DidEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_DidEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DidEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.DidEntityOuterClass.DidEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        did_ = "";
        identifier_ = "";
        blockchain_ = "";
        network_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DidEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor;
      }

      @Override
      public DidEntity getDefaultInstanceForType() {
        return DidEntity.getDefaultInstance();
      }

      @Override
      public DidEntity build() {
        DidEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public DidEntity buildPartial() {
        DidEntity result = new DidEntity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(DidEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.did_ = did_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.identifier_ = identifier_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.blockchain_ = blockchain_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.network_ = network_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DidEntity) {
          return mergeFrom((DidEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DidEntity other) {
        if (other == DidEntity.getDefaultInstance()) return this;
        if (!other.getDid().isEmpty()) {
          did_ = other.did_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getIdentifier().isEmpty()) {
          identifier_ = other.identifier_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getBlockchain().isEmpty()) {
          blockchain_ = other.blockchain_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getNetwork().isEmpty()) {
          network_ = other.network_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                did_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                identifier_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                blockchain_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                network_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object did_ = "";
      /**
       * <code>string did = 1;</code>
       * @return The did.
       */
      public String getDid() {
        Object ref = did_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          did_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @return The bytes for did.
       */
      public com.google.protobuf.ByteString
          getDidBytes() {
        Object ref = did_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          did_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @param value The did to set.
       * @return This builder for chaining.
       */
      public Builder setDid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDid() {
        did_ = getDefaultInstance().getDid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @param value The bytes for did to set.
       * @return This builder for chaining.
       */
      public Builder setDidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object identifier_ = "";
      /**
       * <code>string identifier = 2;</code>
       * @return The identifier.
       */
      public String getIdentifier() {
        Object ref = identifier_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          identifier_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string identifier = 2;</code>
       * @return The bytes for identifier.
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string identifier = 2;</code>
       * @param value The identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifier(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        identifier_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string identifier = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentifier() {
        identifier_ = getDefaultInstance().getIdentifier();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string identifier = 2;</code>
       * @param value The bytes for identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        identifier_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object blockchain_ = "";
      /**
       * <code>string blockchain = 3;</code>
       * @return The blockchain.
       */
      public String getBlockchain() {
        Object ref = blockchain_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          blockchain_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string blockchain = 3;</code>
       * @return The bytes for blockchain.
       */
      public com.google.protobuf.ByteString
          getBlockchainBytes() {
        Object ref = blockchain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          blockchain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blockchain = 3;</code>
       * @param value The blockchain to set.
       * @return This builder for chaining.
       */
      public Builder setBlockchain(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        blockchain_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockchain() {
        blockchain_ = getDefaultInstance().getBlockchain();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain = 3;</code>
       * @param value The bytes for blockchain to set.
       * @return This builder for chaining.
       */
      public Builder setBlockchainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        blockchain_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object network_ = "";
      /**
       * <code>string network = 4;</code>
       * @return The network.
       */
      public String getNetwork() {
        Object ref = network_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          network_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string network = 4;</code>
       * @return The bytes for network.
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        Object ref = network_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          network_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string network = 4;</code>
       * @param value The network to set.
       * @return This builder for chaining.
       */
      public Builder setNetwork(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        network_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string network = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetwork() {
        network_ = getDefaultInstance().getNetwork();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string network = 4;</code>
       * @param value The bytes for network to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        network_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.DidEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.DidEntity)
    private static final DidEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new DidEntity();
    }

    public static DidEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DidEntity>
        PARSER = new com.google.protobuf.AbstractParser<DidEntity>() {
      @Override
      public DidEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<DidEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<DidEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public DidEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_DidEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020did_entity.proto\022%technology.polygon.p" +
      "olygonid_protobuf\"Q\n\tDidEntity\022\013\n\003did\030\001 " +
      "\001(\t\022\022\n\nidentifier\030\002 \001(\t\022\022\n\nblockchain\030\003 " +
      "\001(\t\022\017\n\007network\030\004 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_DidEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_DidEntity_descriptor,
        new String[] { "Did", "Identifier", "Blockchain", "Network", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
