// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: env_entity.proto

package technology.polygon.polygonid_protobuf;

public final class EnvEntityOuterClass {
  private EnvEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EnvEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.EnvEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string blockchain = 1;</code>
     * @return The blockchain.
     */
    String getBlockchain();
    /**
     * <code>string blockchain = 1;</code>
     * @return The bytes for blockchain.
     */
    com.google.protobuf.ByteString
        getBlockchainBytes();

    /**
     * <code>string network = 2;</code>
     * @return The network.
     */
    String getNetwork();
    /**
     * <code>string network = 2;</code>
     * @return The bytes for network.
     */
    com.google.protobuf.ByteString
        getNetworkBytes();

    /**
     * <code>string web3Url = 3;</code>
     * @return The web3Url.
     */
    String getWeb3Url();
    /**
     * <code>string web3Url = 3;</code>
     * @return The bytes for web3Url.
     */
    com.google.protobuf.ByteString
        getWeb3UrlBytes();

    /**
     * <code>string web3RdpUrl = 4;</code>
     * @return The web3RdpUrl.
     */
    String getWeb3RdpUrl();
    /**
     * <code>string web3RdpUrl = 4;</code>
     * @return The bytes for web3RdpUrl.
     */
    com.google.protobuf.ByteString
        getWeb3RdpUrlBytes();

    /**
     * <code>string web3ApiKey = 5;</code>
     * @return The web3ApiKey.
     */
    String getWeb3ApiKey();
    /**
     * <code>string web3ApiKey = 5;</code>
     * @return The bytes for web3ApiKey.
     */
    com.google.protobuf.ByteString
        getWeb3ApiKeyBytes();

    /**
     * <code>string idStateContract = 6;</code>
     * @return The idStateContract.
     */
    String getIdStateContract();
    /**
     * <code>string idStateContract = 6;</code>
     * @return The bytes for idStateContract.
     */
    com.google.protobuf.ByteString
        getIdStateContractBytes();

    /**
     * <code>string pushUrl = 7;</code>
     * @return The pushUrl.
     */
    String getPushUrl();
    /**
     * <code>string pushUrl = 7;</code>
     * @return The bytes for pushUrl.
     */
    com.google.protobuf.ByteString
        getPushUrlBytes();
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.EnvEntity}
   */
  public static final class EnvEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.EnvEntity)
      EnvEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnvEntity.newBuilder() to construct.
    private EnvEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnvEntity() {
      blockchain_ = "";
      network_ = "";
      web3Url_ = "";
      web3RdpUrl_ = "";
      web3ApiKey_ = "";
      idStateContract_ = "";
      pushUrl_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new EnvEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EnvEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EnvEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_EnvEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EnvEntity.class, Builder.class);
    }

    public static final int BLOCKCHAIN_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object blockchain_ = "";
    /**
     * <code>string blockchain = 1;</code>
     * @return The blockchain.
     */
    @Override
    public String getBlockchain() {
      Object ref = blockchain_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        blockchain_ = s;
        return s;
      }
    }
    /**
     * <code>string blockchain = 1;</code>
     * @return The bytes for blockchain.
     */
    @Override
    public com.google.protobuf.ByteString
        getBlockchainBytes() {
      Object ref = blockchain_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        blockchain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NETWORK_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object network_ = "";
    /**
     * <code>string network = 2;</code>
     * @return The network.
     */
    @Override
    public String getNetwork() {
      Object ref = network_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        network_ = s;
        return s;
      }
    }
    /**
     * <code>string network = 2;</code>
     * @return The bytes for network.
     */
    @Override
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      Object ref = network_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEB3URL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object web3Url_ = "";
    /**
     * <code>string web3Url = 3;</code>
     * @return The web3Url.
     */
    @Override
    public String getWeb3Url() {
      Object ref = web3Url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        web3Url_ = s;
        return s;
      }
    }
    /**
     * <code>string web3Url = 3;</code>
     * @return The bytes for web3Url.
     */
    @Override
    public com.google.protobuf.ByteString
        getWeb3UrlBytes() {
      Object ref = web3Url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        web3Url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEB3RDPURL_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object web3RdpUrl_ = "";
    /**
     * <code>string web3RdpUrl = 4;</code>
     * @return The web3RdpUrl.
     */
    @Override
    public String getWeb3RdpUrl() {
      Object ref = web3RdpUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        web3RdpUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string web3RdpUrl = 4;</code>
     * @return The bytes for web3RdpUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getWeb3RdpUrlBytes() {
      Object ref = web3RdpUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        web3RdpUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEB3APIKEY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile Object web3ApiKey_ = "";
    /**
     * <code>string web3ApiKey = 5;</code>
     * @return The web3ApiKey.
     */
    @Override
    public String getWeb3ApiKey() {
      Object ref = web3ApiKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        web3ApiKey_ = s;
        return s;
      }
    }
    /**
     * <code>string web3ApiKey = 5;</code>
     * @return The bytes for web3ApiKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getWeb3ApiKeyBytes() {
      Object ref = web3ApiKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        web3ApiKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDSTATECONTRACT_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile Object idStateContract_ = "";
    /**
     * <code>string idStateContract = 6;</code>
     * @return The idStateContract.
     */
    @Override
    public String getIdStateContract() {
      Object ref = idStateContract_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        idStateContract_ = s;
        return s;
      }
    }
    /**
     * <code>string idStateContract = 6;</code>
     * @return The bytes for idStateContract.
     */
    @Override
    public com.google.protobuf.ByteString
        getIdStateContractBytes() {
      Object ref = idStateContract_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        idStateContract_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSHURL_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile Object pushUrl_ = "";
    /**
     * <code>string pushUrl = 7;</code>
     * @return The pushUrl.
     */
    @Override
    public String getPushUrl() {
      Object ref = pushUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        pushUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string pushUrl = 7;</code>
     * @return The bytes for pushUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getPushUrlBytes() {
      Object ref = pushUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        pushUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockchain_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, blockchain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, network_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3Url_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, web3Url_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3RdpUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, web3RdpUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3ApiKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, web3ApiKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStateContract_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, idStateContract_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pushUrl_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pushUrl_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(blockchain_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, blockchain_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(network_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, network_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3Url_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, web3Url_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3RdpUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, web3RdpUrl_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(web3ApiKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, web3ApiKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(idStateContract_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, idStateContract_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(pushUrl_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pushUrl_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof EnvEntity)) {
        return super.equals(obj);
      }
      EnvEntity other = (EnvEntity) obj;

      if (!getBlockchain()
          .equals(other.getBlockchain())) return false;
      if (!getNetwork()
          .equals(other.getNetwork())) return false;
      if (!getWeb3Url()
          .equals(other.getWeb3Url())) return false;
      if (!getWeb3RdpUrl()
          .equals(other.getWeb3RdpUrl())) return false;
      if (!getWeb3ApiKey()
          .equals(other.getWeb3ApiKey())) return false;
      if (!getIdStateContract()
          .equals(other.getIdStateContract())) return false;
      if (!getPushUrl()
          .equals(other.getPushUrl())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BLOCKCHAIN_FIELD_NUMBER;
      hash = (53 * hash) + getBlockchain().hashCode();
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getNetwork().hashCode();
      hash = (37 * hash) + WEB3URL_FIELD_NUMBER;
      hash = (53 * hash) + getWeb3Url().hashCode();
      hash = (37 * hash) + WEB3RDPURL_FIELD_NUMBER;
      hash = (53 * hash) + getWeb3RdpUrl().hashCode();
      hash = (37 * hash) + WEB3APIKEY_FIELD_NUMBER;
      hash = (53 * hash) + getWeb3ApiKey().hashCode();
      hash = (37 * hash) + IDSTATECONTRACT_FIELD_NUMBER;
      hash = (53 * hash) + getIdStateContract().hashCode();
      hash = (37 * hash) + PUSHURL_FIELD_NUMBER;
      hash = (53 * hash) + getPushUrl().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static EnvEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EnvEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EnvEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EnvEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static EnvEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static EnvEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static EnvEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static EnvEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(EnvEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.EnvEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.EnvEntity)
        EnvEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EnvEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EnvEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_EnvEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EnvEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.EnvEntityOuterClass.EnvEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        blockchain_ = "";
        network_ = "";
        web3Url_ = "";
        web3RdpUrl_ = "";
        web3ApiKey_ = "";
        idStateContract_ = "";
        pushUrl_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EnvEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor;
      }

      @Override
      public EnvEntity getDefaultInstanceForType() {
        return EnvEntity.getDefaultInstance();
      }

      @Override
      public EnvEntity build() {
        EnvEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public EnvEntity buildPartial() {
        EnvEntity result = new EnvEntity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(EnvEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.blockchain_ = blockchain_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.network_ = network_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.web3Url_ = web3Url_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.web3RdpUrl_ = web3RdpUrl_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.web3ApiKey_ = web3ApiKey_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.idStateContract_ = idStateContract_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.pushUrl_ = pushUrl_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EnvEntity) {
          return mergeFrom((EnvEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EnvEntity other) {
        if (other == EnvEntity.getDefaultInstance()) return this;
        if (!other.getBlockchain().isEmpty()) {
          blockchain_ = other.blockchain_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getNetwork().isEmpty()) {
          network_ = other.network_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getWeb3Url().isEmpty()) {
          web3Url_ = other.web3Url_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getWeb3RdpUrl().isEmpty()) {
          web3RdpUrl_ = other.web3RdpUrl_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getWeb3ApiKey().isEmpty()) {
          web3ApiKey_ = other.web3ApiKey_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getIdStateContract().isEmpty()) {
          idStateContract_ = other.idStateContract_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getPushUrl().isEmpty()) {
          pushUrl_ = other.pushUrl_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                blockchain_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                network_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                web3Url_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                web3RdpUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                web3ApiKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                idStateContract_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                pushUrl_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object blockchain_ = "";
      /**
       * <code>string blockchain = 1;</code>
       * @return The blockchain.
       */
      public String getBlockchain() {
        Object ref = blockchain_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          blockchain_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string blockchain = 1;</code>
       * @return The bytes for blockchain.
       */
      public com.google.protobuf.ByteString
          getBlockchainBytes() {
        Object ref = blockchain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          blockchain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blockchain = 1;</code>
       * @param value The blockchain to set.
       * @return This builder for chaining.
       */
      public Builder setBlockchain(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        blockchain_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBlockchain() {
        blockchain_ = getDefaultInstance().getBlockchain();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string blockchain = 1;</code>
       * @param value The bytes for blockchain to set.
       * @return This builder for chaining.
       */
      public Builder setBlockchainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        blockchain_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object network_ = "";
      /**
       * <code>string network = 2;</code>
       * @return The network.
       */
      public String getNetwork() {
        Object ref = network_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          network_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string network = 2;</code>
       * @return The bytes for network.
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        Object ref = network_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          network_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string network = 2;</code>
       * @param value The network to set.
       * @return This builder for chaining.
       */
      public Builder setNetwork(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        network_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string network = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNetwork() {
        network_ = getDefaultInstance().getNetwork();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string network = 2;</code>
       * @param value The bytes for network to set.
       * @return This builder for chaining.
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        network_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object web3Url_ = "";
      /**
       * <code>string web3Url = 3;</code>
       * @return The web3Url.
       */
      public String getWeb3Url() {
        Object ref = web3Url_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          web3Url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string web3Url = 3;</code>
       * @return The bytes for web3Url.
       */
      public com.google.protobuf.ByteString
          getWeb3UrlBytes() {
        Object ref = web3Url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          web3Url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string web3Url = 3;</code>
       * @param value The web3Url to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3Url(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        web3Url_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string web3Url = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeb3Url() {
        web3Url_ = getDefaultInstance().getWeb3Url();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string web3Url = 3;</code>
       * @param value The bytes for web3Url to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3UrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        web3Url_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object web3RdpUrl_ = "";
      /**
       * <code>string web3RdpUrl = 4;</code>
       * @return The web3RdpUrl.
       */
      public String getWeb3RdpUrl() {
        Object ref = web3RdpUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          web3RdpUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string web3RdpUrl = 4;</code>
       * @return The bytes for web3RdpUrl.
       */
      public com.google.protobuf.ByteString
          getWeb3RdpUrlBytes() {
        Object ref = web3RdpUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          web3RdpUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string web3RdpUrl = 4;</code>
       * @param value The web3RdpUrl to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3RdpUrl(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        web3RdpUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string web3RdpUrl = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeb3RdpUrl() {
        web3RdpUrl_ = getDefaultInstance().getWeb3RdpUrl();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string web3RdpUrl = 4;</code>
       * @param value The bytes for web3RdpUrl to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3RdpUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        web3RdpUrl_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private Object web3ApiKey_ = "";
      /**
       * <code>string web3ApiKey = 5;</code>
       * @return The web3ApiKey.
       */
      public String getWeb3ApiKey() {
        Object ref = web3ApiKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          web3ApiKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string web3ApiKey = 5;</code>
       * @return The bytes for web3ApiKey.
       */
      public com.google.protobuf.ByteString
          getWeb3ApiKeyBytes() {
        Object ref = web3ApiKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          web3ApiKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string web3ApiKey = 5;</code>
       * @param value The web3ApiKey to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3ApiKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        web3ApiKey_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string web3ApiKey = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWeb3ApiKey() {
        web3ApiKey_ = getDefaultInstance().getWeb3ApiKey();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string web3ApiKey = 5;</code>
       * @param value The bytes for web3ApiKey to set.
       * @return This builder for chaining.
       */
      public Builder setWeb3ApiKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        web3ApiKey_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private Object idStateContract_ = "";
      /**
       * <code>string idStateContract = 6;</code>
       * @return The idStateContract.
       */
      public String getIdStateContract() {
        Object ref = idStateContract_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          idStateContract_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string idStateContract = 6;</code>
       * @return The bytes for idStateContract.
       */
      public com.google.protobuf.ByteString
          getIdStateContractBytes() {
        Object ref = idStateContract_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          idStateContract_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string idStateContract = 6;</code>
       * @param value The idStateContract to set.
       * @return This builder for chaining.
       */
      public Builder setIdStateContract(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        idStateContract_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string idStateContract = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdStateContract() {
        idStateContract_ = getDefaultInstance().getIdStateContract();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string idStateContract = 6;</code>
       * @param value The bytes for idStateContract to set.
       * @return This builder for chaining.
       */
      public Builder setIdStateContractBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        idStateContract_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private Object pushUrl_ = "";
      /**
       * <code>string pushUrl = 7;</code>
       * @return The pushUrl.
       */
      public String getPushUrl() {
        Object ref = pushUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          pushUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string pushUrl = 7;</code>
       * @return The bytes for pushUrl.
       */
      public com.google.protobuf.ByteString
          getPushUrlBytes() {
        Object ref = pushUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          pushUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string pushUrl = 7;</code>
       * @param value The pushUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPushUrl(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        pushUrl_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string pushUrl = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearPushUrl() {
        pushUrl_ = getDefaultInstance().getPushUrl();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string pushUrl = 7;</code>
       * @param value The bytes for pushUrl to set.
       * @return This builder for chaining.
       */
      public Builder setPushUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        pushUrl_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.EnvEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.EnvEntity)
    private static final EnvEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new EnvEntity();
    }

    public static EnvEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnvEntity>
        PARSER = new com.google.protobuf.AbstractParser<EnvEntity>() {
      @Override
      public EnvEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<EnvEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<EnvEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public EnvEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_EnvEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020env_entity.proto\022%technology.polygon.p" +
      "olygonid_protobuf\"\223\001\n\tEnvEntity\022\022\n\nblock" +
      "chain\030\001 \001(\t\022\017\n\007network\030\002 \001(\t\022\017\n\007web3Url\030" +
      "\003 \001(\t\022\022\n\nweb3RdpUrl\030\004 \001(\t\022\022\n\nweb3ApiKey\030" +
      "\005 \001(\t\022\027\n\017idStateContract\030\006 \001(\t\022\017\n\007pushUr" +
      "l\030\007 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_EnvEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_EnvEntity_descriptor,
        new String[] { "Blockchain", "Network", "Web3Url", "Web3RdpUrl", "Web3ApiKey", "IdStateContract", "PushUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
