// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: field_options.proto

package technology.polygon.polygonid_protobuf;

public final class FieldOptions {
  private FieldOptions() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(FieldOptions.isOptional);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int IS_OPTIONAL_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      Boolean> isOptional = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        Boolean.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023field_options.proto\022%technology.polygo" +
      "n.polygonid_protobuf\032 google/protobuf/de" +
      "scriptor.proto:4\n\013is_optional\022\035.google.p" +
      "rotobuf.FieldOptions\030\321\206\003 \001(\010B\'\n%technolo" +
      "gy.polygon.polygonid_protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    isOptional.internalInit(descriptor.getExtensions().get(0));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
