// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: identity_entity.proto

package technology.polygon.polygonid_protobuf;

public final class IdentityEntityOuterClass {
  private IdentityEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface IdentityEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.IdentityEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    String getDid();
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    com.google.protobuf.ByteString
        getDidBytes();

    /**
     * <code>repeated string publicKey = 2;</code>
     * @return A list containing the publicKey.
     */
    java.util.List<String>
        getPublicKeyList();
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return The count of publicKey.
     */
    int getPublicKeyCount();
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the element to return.
     * @return The publicKey at the given index.
     */
    String getPublicKey(int index);
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publicKey at the given index.
     */
    com.google.protobuf.ByteString
        getPublicKeyBytes(int index);

    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    int getProfilesCount();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    boolean containsProfiles(
        long key);
    /**
     * Use {@link #getProfilesMap()} instead.
     */
    @Deprecated
    java.util.Map<Long, String>
    getProfiles();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    java.util.Map<Long, String>
    getProfilesMap();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    /* nullable */
String getProfilesOrDefault(
        long key,
        /* nullable */
String defaultValue);
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    String getProfilesOrThrow(
        long key);
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.IdentityEntity}
   */
  public static final class IdentityEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.IdentityEntity)
      IdentityEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdentityEntity.newBuilder() to construct.
    private IdentityEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdentityEntity() {
      did_ = "";
      publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new IdentityEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProfiles();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IdentityEntity.class, Builder.class);
    }

    public static final int DID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object did_ = "";
    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    @Override
    public String getDid() {
      Object ref = did_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        did_ = s;
        return s;
      }
    }
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    @Override
    public com.google.protobuf.ByteString
        getDidBytes() {
      Object ref = did_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        did_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList publicKey_;
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return A list containing the publicKey.
     */
    public com.google.protobuf.ProtocolStringList
        getPublicKeyList() {
      return publicKey_;
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return The count of publicKey.
     */
    public int getPublicKeyCount() {
      return publicKey_.size();
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the element to return.
     * @return The publicKey at the given index.
     */
    public String getPublicKey(int index) {
      return publicKey_.get(index);
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publicKey at the given index.
     */
    public com.google.protobuf.ByteString
        getPublicKeyBytes(int index) {
      return publicKey_.getByteString(index);
    }

    public static final int PROFILES_FIELD_NUMBER = 3;
    private static final class ProfilesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Long, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<Long, String>newDefaultInstance(
                  IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        Long, String> profiles_;
    private com.google.protobuf.MapField<Long, String>
    internalGetProfiles() {
      if (profiles_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProfilesDefaultEntryHolder.defaultEntry);
      }
      return profiles_;
    }
    public int getProfilesCount() {
      return internalGetProfiles().getMap().size();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public boolean containsProfiles(
        long key) {
      
      return internalGetProfiles().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProfilesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<Long, String> getProfiles() {
      return getProfilesMap();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public java.util.Map<Long, String> getProfilesMap() {
      return internalGetProfiles().getMap();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public /* nullable */
String getProfilesOrDefault(
        long key,
        /* nullable */
String defaultValue) {
      
      java.util.Map<Long, String> map =
          internalGetProfiles().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public String getProfilesOrThrow(
        long key) {
      
      java.util.Map<Long, String> map =
          internalGetProfiles().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, did_);
      }
      for (int i = 0; i < publicKey_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, publicKey_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetProfiles(),
          ProfilesDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, did_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < publicKey_.size(); i++) {
          dataSize += computeStringSizeNoTag(publicKey_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPublicKeyList().size();
      }
      for (java.util.Map.Entry<Long, String> entry
           : internalGetProfiles().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Long, String>
        profiles__ = ProfilesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, profiles__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IdentityEntity)) {
        return super.equals(obj);
      }
      IdentityEntity other = (IdentityEntity) obj;

      if (!getDid()
          .equals(other.getDid())) return false;
      if (!getPublicKeyList()
          .equals(other.getPublicKeyList())) return false;
      if (!internalGetProfiles().equals(
          other.internalGetProfiles())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DID_FIELD_NUMBER;
      hash = (53 * hash) + getDid().hashCode();
      if (getPublicKeyCount() > 0) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKeyList().hashCode();
      }
      if (!internalGetProfiles().getMap().isEmpty()) {
        hash = (37 * hash) + PROFILES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProfiles().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IdentityEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IdentityEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IdentityEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IdentityEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IdentityEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IdentityEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IdentityEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IdentityEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IdentityEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.IdentityEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.IdentityEntity)
        IdentityEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProfiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProfiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IdentityEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.IdentityEntityOuterClass.IdentityEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        did_ = "";
        publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableProfiles().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor;
      }

      @Override
      public IdentityEntity getDefaultInstanceForType() {
        return IdentityEntity.getDefaultInstance();
      }

      @Override
      public IdentityEntity build() {
        IdentityEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public IdentityEntity buildPartial() {
        IdentityEntity result = new IdentityEntity(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(IdentityEntity result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          publicKey_ = publicKey_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.publicKey_ = publicKey_;
      }

      private void buildPartial0(IdentityEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.did_ = did_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.profiles_ = internalGetProfiles();
          result.profiles_.makeImmutable();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IdentityEntity) {
          return mergeFrom((IdentityEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IdentityEntity other) {
        if (other == IdentityEntity.getDefaultInstance()) return this;
        if (!other.getDid().isEmpty()) {
          did_ = other.did_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.publicKey_.isEmpty()) {
          if (publicKey_.isEmpty()) {
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePublicKeyIsMutable();
            publicKey_.addAll(other.publicKey_);
          }
          onChanged();
        }
        internalGetMutableProfiles().mergeFrom(
            other.internalGetProfiles());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                did_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                String s = input.readStringRequireUtf8();
                ensurePublicKeyIsMutable();
                publicKey_.add(s);
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<Long, String>
                profiles__ = input.readMessage(
                    ProfilesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableProfiles().getMutableMap().put(
                    profiles__.getKey(), profiles__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object did_ = "";
      /**
       * <code>string did = 1;</code>
       * @return The did.
       */
      public String getDid() {
        Object ref = did_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          did_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @return The bytes for did.
       */
      public com.google.protobuf.ByteString
          getDidBytes() {
        Object ref = did_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          did_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @param value The did to set.
       * @return This builder for chaining.
       */
      public Builder setDid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDid() {
        did_ = getDefaultInstance().getDid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @param value The bytes for did to set.
       * @return This builder for chaining.
       */
      public Builder setDidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePublicKeyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          publicKey_ = new com.google.protobuf.LazyStringArrayList(publicKey_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return A list containing the publicKey.
       */
      public com.google.protobuf.ProtocolStringList
          getPublicKeyList() {
        return publicKey_.getUnmodifiableView();
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return The count of publicKey.
       */
      public int getPublicKeyCount() {
        return publicKey_.size();
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index of the element to return.
       * @return The publicKey at the given index.
       */
      public String getPublicKey(int index) {
        return publicKey_.get(index);
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the publicKey at the given index.
       */
      public com.google.protobuf.ByteString
          getPublicKeyBytes(int index) {
        return publicKey_.getByteString(index);
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index to set the value at.
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePublicKeyIsMutable();
        publicKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param value The publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addPublicKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param values The publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addAllPublicKey(
          Iterable<String> values) {
        ensurePublicKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publicKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param value The bytes of the publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          Long, String> profiles_;
      private com.google.protobuf.MapField<Long, String>
          internalGetProfiles() {
        if (profiles_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ProfilesDefaultEntryHolder.defaultEntry);
        }
        return profiles_;
      }
      private com.google.protobuf.MapField<Long, String>
          internalGetMutableProfiles() {
        if (profiles_ == null) {
          profiles_ = com.google.protobuf.MapField.newMapField(
              ProfilesDefaultEntryHolder.defaultEntry);
        }
        if (!profiles_.isMutable()) {
          profiles_ = profiles_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return profiles_;
      }
      public int getProfilesCount() {
        return internalGetProfiles().getMap().size();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public boolean containsProfiles(
          long key) {
        
        return internalGetProfiles().getMap().containsKey(key);
      }
      /**
       * Use {@link #getProfilesMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<Long, String> getProfiles() {
        return getProfilesMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public java.util.Map<Long, String> getProfilesMap() {
        return internalGetProfiles().getMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public /* nullable */
String getProfilesOrDefault(
          long key,
          /* nullable */
String defaultValue) {
        
        java.util.Map<Long, String> map =
            internalGetProfiles().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public String getProfilesOrThrow(
          long key) {
        
        java.util.Map<Long, String> map =
            internalGetProfiles().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearProfiles() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableProfiles().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder removeProfiles(
          long key) {
        
        internalGetMutableProfiles().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Long, String>
          getMutableProfiles() {
        bitField0_ |= 0x00000004;
        return internalGetMutableProfiles().getMutableMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder putProfiles(
          long key,
          String value) {
        
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableProfiles().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder putAllProfiles(
          java.util.Map<Long, String> values) {
        internalGetMutableProfiles().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.IdentityEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.IdentityEntity)
    private static final IdentityEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IdentityEntity();
    }

    public static IdentityEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdentityEntity>
        PARSER = new com.google.protobuf.AbstractParser<IdentityEntity>() {
      @Override
      public IdentityEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<IdentityEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<IdentityEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public IdentityEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PrivateIdentityEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.PrivateIdentityEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    String getDid();
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    com.google.protobuf.ByteString
        getDidBytes();

    /**
     * <code>repeated string publicKey = 2;</code>
     * @return A list containing the publicKey.
     */
    java.util.List<String>
        getPublicKeyList();
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return The count of publicKey.
     */
    int getPublicKeyCount();
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the element to return.
     * @return The publicKey at the given index.
     */
    String getPublicKey(int index);
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publicKey at the given index.
     */
    com.google.protobuf.ByteString
        getPublicKeyBytes(int index);

    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    int getProfilesCount();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    boolean containsProfiles(
        long key);
    /**
     * Use {@link #getProfilesMap()} instead.
     */
    @Deprecated
    java.util.Map<Long, String>
    getProfiles();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    java.util.Map<Long, String>
    getProfilesMap();
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    /* nullable */
String getProfilesOrDefault(
        long key,
        /* nullable */
String defaultValue);
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    String getProfilesOrThrow(
        long key);

    /**
     * <code>string privateKey = 4;</code>
     * @return The privateKey.
     */
    String getPrivateKey();
    /**
     * <code>string privateKey = 4;</code>
     * @return The bytes for privateKey.
     */
    com.google.protobuf.ByteString
        getPrivateKeyBytes();
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.PrivateIdentityEntity}
   */
  public static final class PrivateIdentityEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.PrivateIdentityEntity)
      PrivateIdentityEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PrivateIdentityEntity.newBuilder() to construct.
    private PrivateIdentityEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PrivateIdentityEntity() {
      did_ = "";
      publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      privateKey_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PrivateIdentityEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetProfiles();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PrivateIdentityEntity.class, Builder.class);
    }

    public static final int DID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object did_ = "";
    /**
     * <code>string did = 1;</code>
     * @return The did.
     */
    @Override
    public String getDid() {
      Object ref = did_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        did_ = s;
        return s;
      }
    }
    /**
     * <code>string did = 1;</code>
     * @return The bytes for did.
     */
    @Override
    public com.google.protobuf.ByteString
        getDidBytes() {
      Object ref = did_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        did_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBLICKEY_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringList publicKey_;
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return A list containing the publicKey.
     */
    public com.google.protobuf.ProtocolStringList
        getPublicKeyList() {
      return publicKey_;
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @return The count of publicKey.
     */
    public int getPublicKeyCount() {
      return publicKey_.size();
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the element to return.
     * @return The publicKey at the given index.
     */
    public String getPublicKey(int index) {
      return publicKey_.get(index);
    }
    /**
     * <code>repeated string publicKey = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the publicKey at the given index.
     */
    public com.google.protobuf.ByteString
        getPublicKeyBytes(int index) {
      return publicKey_.getByteString(index);
    }

    public static final int PROFILES_FIELD_NUMBER = 3;
    private static final class ProfilesDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          Long, String> defaultEntry =
              com.google.protobuf.MapEntry
              .<Long, String>newDefaultInstance(
                  IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.INT64,
                  0L,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        Long, String> profiles_;
    private com.google.protobuf.MapField<Long, String>
    internalGetProfiles() {
      if (profiles_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ProfilesDefaultEntryHolder.defaultEntry);
      }
      return profiles_;
    }
    public int getProfilesCount() {
      return internalGetProfiles().getMap().size();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public boolean containsProfiles(
        long key) {
      
      return internalGetProfiles().getMap().containsKey(key);
    }
    /**
     * Use {@link #getProfilesMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<Long, String> getProfiles() {
      return getProfilesMap();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public java.util.Map<Long, String> getProfilesMap() {
      return internalGetProfiles().getMap();
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public /* nullable */
String getProfilesOrDefault(
        long key,
        /* nullable */
String defaultValue) {
      
      java.util.Map<Long, String> map =
          internalGetProfiles().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int64, string&gt; profiles = 3;</code>
     */
    @Override
    public String getProfilesOrThrow(
        long key) {
      
      java.util.Map<Long, String> map =
          internalGetProfiles().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int PRIVATEKEY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object privateKey_ = "";
    /**
     * <code>string privateKey = 4;</code>
     * @return The privateKey.
     */
    @Override
    public String getPrivateKey() {
      Object ref = privateKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        privateKey_ = s;
        return s;
      }
    }
    /**
     * <code>string privateKey = 4;</code>
     * @return The bytes for privateKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      Object ref = privateKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        privateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, did_);
      }
      for (int i = 0; i < publicKey_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, publicKey_.getRaw(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeLongMapTo(
          output,
          internalGetProfiles(),
          ProfilesDefaultEntryHolder.defaultEntry,
          3);
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(privateKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, privateKey_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(did_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, did_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < publicKey_.size(); i++) {
          dataSize += computeStringSizeNoTag(publicKey_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPublicKeyList().size();
      }
      for (java.util.Map.Entry<Long, String> entry
           : internalGetProfiles().getMap().entrySet()) {
        com.google.protobuf.MapEntry<Long, String>
        profiles__ = ProfilesDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, profiles__);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(privateKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, privateKey_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PrivateIdentityEntity)) {
        return super.equals(obj);
      }
      PrivateIdentityEntity other = (PrivateIdentityEntity) obj;

      if (!getDid()
          .equals(other.getDid())) return false;
      if (!getPublicKeyList()
          .equals(other.getPublicKeyList())) return false;
      if (!internalGetProfiles().equals(
          other.internalGetProfiles())) return false;
      if (!getPrivateKey()
          .equals(other.getPrivateKey())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DID_FIELD_NUMBER;
      hash = (53 * hash) + getDid().hashCode();
      if (getPublicKeyCount() > 0) {
        hash = (37 * hash) + PUBLICKEY_FIELD_NUMBER;
        hash = (53 * hash) + getPublicKeyList().hashCode();
      }
      if (!internalGetProfiles().getMap().isEmpty()) {
        hash = (37 * hash) + PROFILES_FIELD_NUMBER;
        hash = (53 * hash) + internalGetProfiles().hashCode();
      }
      hash = (37 * hash) + PRIVATEKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PrivateIdentityEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PrivateIdentityEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PrivateIdentityEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PrivateIdentityEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PrivateIdentityEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PrivateIdentityEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PrivateIdentityEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PrivateIdentityEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PrivateIdentityEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PrivateIdentityEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PrivateIdentityEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PrivateIdentityEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PrivateIdentityEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.PrivateIdentityEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.PrivateIdentityEntity)
        PrivateIdentityEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetProfiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableProfiles();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PrivateIdentityEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.IdentityEntityOuterClass.PrivateIdentityEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        did_ = "";
        publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableProfiles().clear();
        privateKey_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IdentityEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor;
      }

      @Override
      public PrivateIdentityEntity getDefaultInstanceForType() {
        return PrivateIdentityEntity.getDefaultInstance();
      }

      @Override
      public PrivateIdentityEntity build() {
        PrivateIdentityEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PrivateIdentityEntity buildPartial() {
        PrivateIdentityEntity result = new PrivateIdentityEntity(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(PrivateIdentityEntity result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          publicKey_ = publicKey_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.publicKey_ = publicKey_;
      }

      private void buildPartial0(PrivateIdentityEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.did_ = did_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.profiles_ = internalGetProfiles();
          result.profiles_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.privateKey_ = privateKey_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PrivateIdentityEntity) {
          return mergeFrom((PrivateIdentityEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PrivateIdentityEntity other) {
        if (other == PrivateIdentityEntity.getDefaultInstance()) return this;
        if (!other.getDid().isEmpty()) {
          did_ = other.did_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.publicKey_.isEmpty()) {
          if (publicKey_.isEmpty()) {
            publicKey_ = other.publicKey_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensurePublicKeyIsMutable();
            publicKey_.addAll(other.publicKey_);
          }
          onChanged();
        }
        internalGetMutableProfiles().mergeFrom(
            other.internalGetProfiles());
        bitField0_ |= 0x00000004;
        if (!other.getPrivateKey().isEmpty()) {
          privateKey_ = other.privateKey_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                did_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                String s = input.readStringRequireUtf8();
                ensurePublicKeyIsMutable();
                publicKey_.add(s);
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<Long, String>
                profiles__ = input.readMessage(
                    ProfilesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableProfiles().getMutableMap().put(
                    profiles__.getKey(), profiles__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                privateKey_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object did_ = "";
      /**
       * <code>string did = 1;</code>
       * @return The did.
       */
      public String getDid() {
        Object ref = did_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          did_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @return The bytes for did.
       */
      public com.google.protobuf.ByteString
          getDidBytes() {
        Object ref = did_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          did_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string did = 1;</code>
       * @param value The did to set.
       * @return This builder for chaining.
       */
      public Builder setDid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDid() {
        did_ = getDefaultInstance().getDid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string did = 1;</code>
       * @param value The bytes for did to set.
       * @return This builder for chaining.
       */
      public Builder setDidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        did_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensurePublicKeyIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          publicKey_ = new com.google.protobuf.LazyStringArrayList(publicKey_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return A list containing the publicKey.
       */
      public com.google.protobuf.ProtocolStringList
          getPublicKeyList() {
        return publicKey_.getUnmodifiableView();
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return The count of publicKey.
       */
      public int getPublicKeyCount() {
        return publicKey_.size();
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index of the element to return.
       * @return The publicKey at the given index.
       */
      public String getPublicKey(int index) {
        return publicKey_.get(index);
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the publicKey at the given index.
       */
      public com.google.protobuf.ByteString
          getPublicKeyBytes(int index) {
        return publicKey_.getByteString(index);
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param index The index to set the value at.
       * @param value The publicKey to set.
       * @return This builder for chaining.
       */
      public Builder setPublicKey(
          int index, String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePublicKeyIsMutable();
        publicKey_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param value The publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addPublicKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param values The publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addAllPublicKey(
          Iterable<String> values) {
        ensurePublicKeyIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, publicKey_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPublicKey() {
        publicKey_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string publicKey = 2;</code>
       * @param value The bytes of the publicKey to add.
       * @return This builder for chaining.
       */
      public Builder addPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePublicKeyIsMutable();
        publicKey_.add(value);
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          Long, String> profiles_;
      private com.google.protobuf.MapField<Long, String>
          internalGetProfiles() {
        if (profiles_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ProfilesDefaultEntryHolder.defaultEntry);
        }
        return profiles_;
      }
      private com.google.protobuf.MapField<Long, String>
          internalGetMutableProfiles() {
        if (profiles_ == null) {
          profiles_ = com.google.protobuf.MapField.newMapField(
              ProfilesDefaultEntryHolder.defaultEntry);
        }
        if (!profiles_.isMutable()) {
          profiles_ = profiles_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return profiles_;
      }
      public int getProfilesCount() {
        return internalGetProfiles().getMap().size();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public boolean containsProfiles(
          long key) {
        
        return internalGetProfiles().getMap().containsKey(key);
      }
      /**
       * Use {@link #getProfilesMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<Long, String> getProfiles() {
        return getProfilesMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public java.util.Map<Long, String> getProfilesMap() {
        return internalGetProfiles().getMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public /* nullable */
String getProfilesOrDefault(
          long key,
          /* nullable */
String defaultValue) {
        
        java.util.Map<Long, String> map =
            internalGetProfiles().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      @Override
      public String getProfilesOrThrow(
          long key) {
        
        java.util.Map<Long, String> map =
            internalGetProfiles().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearProfiles() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableProfiles().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder removeProfiles(
          long key) {
        
        internalGetMutableProfiles().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<Long, String>
          getMutableProfiles() {
        bitField0_ |= 0x00000004;
        return internalGetMutableProfiles().getMutableMap();
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder putProfiles(
          long key,
          String value) {
        
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableProfiles().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;int64, string&gt; profiles = 3;</code>
       */
      public Builder putAllProfiles(
          java.util.Map<Long, String> values) {
        internalGetMutableProfiles().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }

      private Object privateKey_ = "";
      /**
       * <code>string privateKey = 4;</code>
       * @return The privateKey.
       */
      public String getPrivateKey() {
        Object ref = privateKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          privateKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string privateKey = 4;</code>
       * @return The bytes for privateKey.
       */
      public com.google.protobuf.ByteString
          getPrivateKeyBytes() {
        Object ref = privateKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          privateKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string privateKey = 4;</code>
       * @param value The privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKey(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        privateKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string privateKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrivateKey() {
        privateKey_ = getDefaultInstance().getPrivateKey();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string privateKey = 4;</code>
       * @param value The bytes for privateKey to set.
       * @return This builder for chaining.
       */
      public Builder setPrivateKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        privateKey_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.PrivateIdentityEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.PrivateIdentityEntity)
    private static final PrivateIdentityEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PrivateIdentityEntity();
    }

    public static PrivateIdentityEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PrivateIdentityEntity>
        PARSER = new com.google.protobuf.AbstractParser<PrivateIdentityEntity>() {
      @Override
      public PrivateIdentityEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PrivateIdentityEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PrivateIdentityEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public PrivateIdentityEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025identity_entity.proto\022%technology.poly" +
      "gon.polygonid_protobuf\"\270\001\n\016IdentityEntit" +
      "y\022\013\n\003did\030\001 \001(\t\022\021\n\tpublicKey\030\002 \003(\t\022U\n\010pro" +
      "files\030\003 \003(\0132C.technology.polygon.polygon" +
      "id_protobuf.IdentityEntity.ProfilesEntry" +
      "\032/\n\rProfilesEntry\022\013\n\003key\030\001 \001(\003\022\r\n\005value\030" +
      "\002 \001(\t:\0028\001\"\332\001\n\025PrivateIdentityEntity\022\013\n\003d" +
      "id\030\001 \001(\t\022\021\n\tpublicKey\030\002 \003(\t\022\\\n\010profiles\030" +
      "\003 \003(\0132J.technology.polygon.polygonid_pro" +
      "tobuf.PrivateIdentityEntity.ProfilesEntr" +
      "y\022\022\n\nprivateKey\030\004 \001(\t\032/\n\rProfilesEntry\022\013" +
      "\n\003key\030\001 \001(\003\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor,
        new String[] { "Did", "PublicKey", "Profiles", });
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_descriptor =
      internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_descriptor.getNestedTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_IdentityEntity_ProfilesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor,
        new String[] { "Did", "PublicKey", "Profiles", "PrivateKey", });
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_descriptor =
      internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_descriptor.getNestedTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_PrivateIdentityEntity_ProfilesEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
