// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proof_request_entity.proto

package technology.polygon.polygonid_protobuf;

public final class ProofRequestEntityOuterClass {
  private ProofRequestEntityOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProofRequestEntityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.ProofRequestEntity)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     * @return Whether the scope field is set.
     */
    boolean hasScope();
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     * @return The scope.
     */
    ProofScopeRequestOuterClass.ProofScopeRequest getScope();
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     */
    ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder getScopeOrBuilder();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    int getContextCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    boolean containsContext(
        String key);
    /**
     * Use {@link #getContextMap()} instead.
     */
    @Deprecated
    java.util.Map<String, com.google.protobuf.Value>
    getContext();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    java.util.Map<String, com.google.protobuf.Value>
    getContextMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    /* nullable */
com.google.protobuf.Value getContextOrDefault(
        String key,
        /* nullable */
com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    com.google.protobuf.Value getContextOrThrow(
        String key);

    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     * @return Whether the queryParam field is set.
     */
    boolean hasQueryParam();
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     * @return The queryParam.
     */
    ProofRequestEntity.ProofQueryParamEntity getQueryParam();
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     */
    ProofRequestEntity.ProofQueryParamEntityOrBuilder getQueryParamOrBuilder();
  }
  /**
   * Protobuf type {@code technology.polygon.polygonid_protobuf.ProofRequestEntity}
   */
  public static final class ProofRequestEntity extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.ProofRequestEntity)
      ProofRequestEntityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProofRequestEntity.newBuilder() to construct.
    private ProofRequestEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProofRequestEntity() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProofRequestEntity();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetContext();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProofRequestEntity.class, Builder.class);
    }

    public interface ProofQueryParamEntityOrBuilder extends
        // @@protoc_insertion_point(interface_extends:technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string field = 1;</code>
       * @return The field.
       */
      String getField();
      /**
       * <code>string field = 1;</code>
       * @return The bytes for field.
       */
      com.google.protobuf.ByteString
          getFieldBytes();

      /**
       * <code>repeated int32 values = 2;</code>
       * @return A list containing the values.
       */
      java.util.List<Integer> getValuesList();
      /**
       * <code>repeated int32 values = 2;</code>
       * @return The count of values.
       */
      int getValuesCount();
      /**
       * <code>repeated int32 values = 2;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      int getValues(int index);

      /**
       * <code>int32 operator = 3;</code>
       * @return The operator.
       */
      int getOperator();
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity}
     */
    public static final class ProofQueryParamEntity extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity)
        ProofQueryParamEntityOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ProofQueryParamEntity.newBuilder() to construct.
      private ProofQueryParamEntity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ProofQueryParamEntity() {
        field_ = "";
        values_ = emptyIntList();
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new ProofQueryParamEntity();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProofQueryParamEntity.class, Builder.class);
      }

      public static final int FIELD_FIELD_NUMBER = 1;
      @SuppressWarnings("serial")
      private volatile Object field_ = "";
      /**
       * <code>string field = 1;</code>
       * @return The field.
       */
      @Override
      public String getField() {
        Object ref = field_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          field_ = s;
          return s;
        }
      }
      /**
       * <code>string field = 1;</code>
       * @return The bytes for field.
       */
      @Override
      public com.google.protobuf.ByteString
          getFieldBytes() {
        Object ref = field_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          field_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int VALUES_FIELD_NUMBER = 2;
      @SuppressWarnings("serial")
      private com.google.protobuf.Internal.IntList values_;
      /**
       * <code>repeated int32 values = 2;</code>
       * @return A list containing the values.
       */
      @Override
      public java.util.List<Integer>
          getValuesList() {
        return values_;
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @return The count of values.
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated int32 values = 2;</code>
       * @param index The index of the element to return.
       * @return The values at the given index.
       */
      public int getValues(int index) {
        return values_.getInt(index);
      }
      private int valuesMemoizedSerializedSize = -1;

      public static final int OPERATOR_FIELD_NUMBER = 3;
      private int operator_ = 0;
      /**
       * <code>int32 operator = 3;</code>
       * @return The operator.
       */
      @Override
      public int getOperator() {
        return operator_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field_);
        }
        if (getValuesList().size() > 0) {
          output.writeUInt32NoTag(18);
          output.writeUInt32NoTag(valuesMemoizedSerializedSize);
        }
        for (int i = 0; i < values_.size(); i++) {
          output.writeInt32NoTag(values_.getInt(i));
        }
        if (operator_ != 0) {
          output.writeInt32(3, operator_);
        }
        getUnknownFields().writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < values_.size(); i++) {
            dataSize += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(values_.getInt(i));
          }
          size += dataSize;
          if (!getValuesList().isEmpty()) {
            size += 1;
            size += com.google.protobuf.CodedOutputStream
                .computeInt32SizeNoTag(dataSize);
          }
          valuesMemoizedSerializedSize = dataSize;
        }
        if (operator_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, operator_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProofQueryParamEntity)) {
          return super.equals(obj);
        }
        ProofQueryParamEntity other = (ProofQueryParamEntity) obj;

        if (!getField()
            .equals(other.getField())) return false;
        if (!getValuesList()
            .equals(other.getValuesList())) return false;
        if (getOperator()
            != other.getOperator()) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FIELD_FIELD_NUMBER;
        hash = (53 * hash) + getField().hashCode();
        if (getValuesCount() > 0) {
          hash = (37 * hash) + VALUES_FIELD_NUMBER;
          hash = (53 * hash) + getValuesList().hashCode();
        }
        hash = (37 * hash) + OPERATOR_FIELD_NUMBER;
        hash = (53 * hash) + getOperator();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProofQueryParamEntity parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProofQueryParamEntity parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProofQueryParamEntity parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProofQueryParamEntity parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProofQueryParamEntity parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProofQueryParamEntity parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProofQueryParamEntity parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProofQueryParamEntity parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProofQueryParamEntity parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProofQueryParamEntity parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProofQueryParamEntity parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProofQueryParamEntity parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProofQueryParamEntity prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity)
          ProofQueryParamEntityOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProofQueryParamEntity.class, Builder.class);
        }

        // Construct using technology.polygon.polygonid_protobuf.ProofRequestEntityOuterClass.ProofRequestEntity.ProofQueryParamEntity.newBuilder()
        private Builder() {

        }

        private Builder(
            BuilderParent parent) {
          super(parent);

        }
        @Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          field_ = "";
          values_ = emptyIntList();
          operator_ = 0;
          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor;
        }

        @Override
        public ProofQueryParamEntity getDefaultInstanceForType() {
          return ProofQueryParamEntity.getDefaultInstance();
        }

        @Override
        public ProofQueryParamEntity build() {
          ProofQueryParamEntity result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public ProofQueryParamEntity buildPartial() {
          ProofQueryParamEntity result = new ProofQueryParamEntity(this);
          buildPartialRepeatedFields(result);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartialRepeatedFields(ProofQueryParamEntity result) {
          if (((bitField0_ & 0x00000002) != 0)) {
            values_.makeImmutable();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.values_ = values_;
        }

        private void buildPartial0(ProofQueryParamEntity result) {
          int from_bitField0_ = bitField0_;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.field_ = field_;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            result.operator_ = operator_;
          }
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProofQueryParamEntity) {
            return mergeFrom((ProofQueryParamEntity)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProofQueryParamEntity other) {
          if (other == ProofQueryParamEntity.getDefaultInstance()) return this;
          if (!other.getField().isEmpty()) {
            field_ = other.field_;
            bitField0_ |= 0x00000001;
            onChanged();
          }
          if (!other.values_.isEmpty()) {
            if (values_.isEmpty()) {
              values_ = other.values_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureValuesIsMutable();
              values_.addAll(other.values_);
            }
            onChanged();
          }
          if (other.getOperator() != 0) {
            setOperator(other.getOperator());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 10: {
                  field_ = input.readStringRequireUtf8();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 10
                case 16: {
                  int v = input.readInt32();
                  ensureValuesIsMutable();
                  values_.addInt(v);
                  break;
                } // case 16
                case 18: {
                  int length = input.readRawVarint32();
                  int limit = input.pushLimit(length);
                  ensureValuesIsMutable();
                  while (input.getBytesUntilLimit() > 0) {
                    values_.addInt(input.readInt32());
                  }
                  input.popLimit(limit);
                  break;
                } // case 18
                case 24: {
                  operator_ = input.readInt32();
                  bitField0_ |= 0x00000004;
                  break;
                } // case 24
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private Object field_ = "";
        /**
         * <code>string field = 1;</code>
         * @return The field.
         */
        public String getField() {
          Object ref = field_;
          if (!(ref instanceof String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            field_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        /**
         * <code>string field = 1;</code>
         * @return The bytes for field.
         */
        public com.google.protobuf.ByteString
            getFieldBytes() {
          Object ref = field_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (String) ref);
            field_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string field = 1;</code>
         * @param value The field to set.
         * @return This builder for chaining.
         */
        public Builder setField(
            String value) {
          if (value == null) { throw new NullPointerException(); }
          field_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>string field = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearField() {
          field_ = getDefaultInstance().getField();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>string field = 1;</code>
         * @param value The bytes for field to set.
         * @return This builder for chaining.
         */
        public Builder setFieldBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) { throw new NullPointerException(); }
          checkByteStringIsUtf8(value);
          field_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }

        private com.google.protobuf.Internal.IntList values_ = emptyIntList();
        private void ensureValuesIsMutable() {
          if (!((bitField0_ & 0x00000002) != 0)) {
            values_ = mutableCopy(values_);
            bitField0_ |= 0x00000002;
          }
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @return A list containing the values.
         */
        public java.util.List<Integer>
            getValuesList() {
          return ((bitField0_ & 0x00000002) != 0) ?
                   java.util.Collections.unmodifiableList(values_) : values_;
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @return The count of values.
         */
        public int getValuesCount() {
          return values_.size();
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @param index The index of the element to return.
         * @return The values at the given index.
         */
        public int getValues(int index) {
          return values_.getInt(index);
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @param index The index to set the value at.
         * @param value The values to set.
         * @return This builder for chaining.
         */
        public Builder setValues(
            int index, int value) {
          
          ensureValuesIsMutable();
          values_.setInt(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @param value The values to add.
         * @return This builder for chaining.
         */
        public Builder addValues(int value) {
          
          ensureValuesIsMutable();
          values_.addInt(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @param values The values to add.
         * @return This builder for chaining.
         */
        public Builder addAllValues(
            Iterable<? extends Integer> values) {
          ensureValuesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, values_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated int32 values = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearValues() {
          values_ = emptyIntList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }

        private int operator_ ;
        /**
         * <code>int32 operator = 3;</code>
         * @return The operator.
         */
        @Override
        public int getOperator() {
          return operator_;
        }
        /**
         * <code>int32 operator = 3;</code>
         * @param value The operator to set.
         * @return This builder for chaining.
         */
        public Builder setOperator(int value) {
          
          operator_ = value;
          bitField0_ |= 0x00000004;
          onChanged();
          return this;
        }
        /**
         * <code>int32 operator = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearOperator() {
          bitField0_ = (bitField0_ & ~0x00000004);
          operator_ = 0;
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity)
      }

      // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity)
      private static final ProofQueryParamEntity DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProofQueryParamEntity();
      }

      public static ProofQueryParamEntity getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ProofQueryParamEntity>
          PARSER = new com.google.protobuf.AbstractParser<ProofQueryParamEntity>() {
        @Override
        public ProofQueryParamEntity parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<ProofQueryParamEntity> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<ProofQueryParamEntity> getParserForType() {
        return PARSER;
      }

      @Override
      public ProofQueryParamEntity getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SCOPE_FIELD_NUMBER = 1;
    private ProofScopeRequestOuterClass.ProofScopeRequest scope_;
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     * @return Whether the scope field is set.
     */
    @Override
    public boolean hasScope() {
      return scope_ != null;
    }
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     * @return The scope.
     */
    @Override
    public ProofScopeRequestOuterClass.ProofScopeRequest getScope() {
      return scope_ == null ? ProofScopeRequestOuterClass.ProofScopeRequest.getDefaultInstance() : scope_;
    }
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
     */
    @Override
    public ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder getScopeOrBuilder() {
      return scope_ == null ? ProofScopeRequestOuterClass.ProofScopeRequest.getDefaultInstance() : scope_;
    }

    public static final int CONTEXT_FIELD_NUMBER = 2;
    private static final class ContextDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, com.google.protobuf.Value>newDefaultInstance(
                  ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        String, com.google.protobuf.Value> context_;
    private com.google.protobuf.MapField<String, com.google.protobuf.Value>
    internalGetContext() {
      if (context_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ContextDefaultEntryHolder.defaultEntry);
      }
      return context_;
    }
    public int getContextCount() {
      return internalGetContext().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    @Override
    public boolean containsContext(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetContext().getMap().containsKey(key);
    }
    /**
     * Use {@link #getContextMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, com.google.protobuf.Value> getContext() {
      return getContextMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    @Override
    public java.util.Map<String, com.google.protobuf.Value> getContextMap() {
      return internalGetContext().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    @Override
    public /* nullable */
com.google.protobuf.Value getContextOrDefault(
        String key,
        /* nullable */
com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, com.google.protobuf.Value> map =
          internalGetContext().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
     */
    @Override
    public com.google.protobuf.Value getContextOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<String, com.google.protobuf.Value> map =
          internalGetContext().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int QUERYPARAM_FIELD_NUMBER = 3;
    private ProofQueryParamEntity queryParam_;
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     * @return Whether the queryParam field is set.
     */
    @Override
    public boolean hasQueryParam() {
      return queryParam_ != null;
    }
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     * @return The queryParam.
     */
    @Override
    public ProofQueryParamEntity getQueryParam() {
      return queryParam_ == null ? ProofQueryParamEntity.getDefaultInstance() : queryParam_;
    }
    /**
     * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
     */
    @Override
    public ProofQueryParamEntityOrBuilder getQueryParamOrBuilder() {
      return queryParam_ == null ? ProofQueryParamEntity.getDefaultInstance() : queryParam_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (scope_ != null) {
        output.writeMessage(1, getScope());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetContext(),
          ContextDefaultEntryHolder.defaultEntry,
          2);
      if (queryParam_ != null) {
        output.writeMessage(3, getQueryParam());
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (scope_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getScope());
      }
      for (java.util.Map.Entry<String, com.google.protobuf.Value> entry
           : internalGetContext().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, com.google.protobuf.Value>
        context__ = ContextDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, context__);
      }
      if (queryParam_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getQueryParam());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProofRequestEntity)) {
        return super.equals(obj);
      }
      ProofRequestEntity other = (ProofRequestEntity) obj;

      if (hasScope() != other.hasScope()) return false;
      if (hasScope()) {
        if (!getScope()
            .equals(other.getScope())) return false;
      }
      if (!internalGetContext().equals(
          other.internalGetContext())) return false;
      if (hasQueryParam() != other.hasQueryParam()) return false;
      if (hasQueryParam()) {
        if (!getQueryParam()
            .equals(other.getQueryParam())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasScope()) {
        hash = (37 * hash) + SCOPE_FIELD_NUMBER;
        hash = (53 * hash) + getScope().hashCode();
      }
      if (!internalGetContext().getMap().isEmpty()) {
        hash = (37 * hash) + CONTEXT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetContext().hashCode();
      }
      if (hasQueryParam()) {
        hash = (37 * hash) + QUERYPARAM_FIELD_NUMBER;
        hash = (53 * hash) + getQueryParam().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProofRequestEntity parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProofRequestEntity parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProofRequestEntity parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProofRequestEntity parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProofRequestEntity parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProofRequestEntity parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProofRequestEntity parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProofRequestEntity parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProofRequestEntity parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProofRequestEntity parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProofRequestEntity parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProofRequestEntity parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProofRequestEntity prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code technology.polygon.polygonid_protobuf.ProofRequestEntity}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:technology.polygon.polygonid_protobuf.ProofRequestEntity)
        ProofRequestEntityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetContext();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableContext();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProofRequestEntity.class, Builder.class);
      }

      // Construct using technology.polygon.polygonid_protobuf.ProofRequestEntityOuterClass.ProofRequestEntity.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        scope_ = null;
        if (scopeBuilder_ != null) {
          scopeBuilder_.dispose();
          scopeBuilder_ = null;
        }
        internalGetMutableContext().clear();
        queryParam_ = null;
        if (queryParamBuilder_ != null) {
          queryParamBuilder_.dispose();
          queryParamBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProofRequestEntityOuterClass.internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor;
      }

      @Override
      public ProofRequestEntity getDefaultInstanceForType() {
        return ProofRequestEntity.getDefaultInstance();
      }

      @Override
      public ProofRequestEntity build() {
        ProofRequestEntity result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ProofRequestEntity buildPartial() {
        ProofRequestEntity result = new ProofRequestEntity(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ProofRequestEntity result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.scope_ = scopeBuilder_ == null
              ? scope_
              : scopeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.context_ = internalGetContext();
          result.context_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.queryParam_ = queryParamBuilder_ == null
              ? queryParam_
              : queryParamBuilder_.build();
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProofRequestEntity) {
          return mergeFrom((ProofRequestEntity)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProofRequestEntity other) {
        if (other == ProofRequestEntity.getDefaultInstance()) return this;
        if (other.hasScope()) {
          mergeScope(other.getScope());
        }
        internalGetMutableContext().mergeFrom(
            other.internalGetContext());
        bitField0_ |= 0x00000002;
        if (other.hasQueryParam()) {
          mergeQueryParam(other.getQueryParam());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getScopeFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<String, com.google.protobuf.Value>
                context__ = input.readMessage(
                    ContextDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableContext().getMutableMap().put(
                    context__.getKey(), context__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getQueryParamFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private ProofScopeRequestOuterClass.ProofScopeRequest scope_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProofScopeRequestOuterClass.ProofScopeRequest, ProofScopeRequestOuterClass.ProofScopeRequest.Builder, ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder> scopeBuilder_;
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       * @return Whether the scope field is set.
       */
      public boolean hasScope() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       * @return The scope.
       */
      public ProofScopeRequestOuterClass.ProofScopeRequest getScope() {
        if (scopeBuilder_ == null) {
          return scope_ == null ? ProofScopeRequestOuterClass.ProofScopeRequest.getDefaultInstance() : scope_;
        } else {
          return scopeBuilder_.getMessage();
        }
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public Builder setScope(ProofScopeRequestOuterClass.ProofScopeRequest value) {
        if (scopeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scope_ = value;
        } else {
          scopeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public Builder setScope(
          ProofScopeRequestOuterClass.ProofScopeRequest.Builder builderForValue) {
        if (scopeBuilder_ == null) {
          scope_ = builderForValue.build();
        } else {
          scopeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public Builder mergeScope(ProofScopeRequestOuterClass.ProofScopeRequest value) {
        if (scopeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            scope_ != null &&
            scope_ != ProofScopeRequestOuterClass.ProofScopeRequest.getDefaultInstance()) {
            getScopeBuilder().mergeFrom(value);
          } else {
            scope_ = value;
          }
        } else {
          scopeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public Builder clearScope() {
        bitField0_ = (bitField0_ & ~0x00000001);
        scope_ = null;
        if (scopeBuilder_ != null) {
          scopeBuilder_.dispose();
          scopeBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public ProofScopeRequestOuterClass.ProofScopeRequest.Builder getScopeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getScopeFieldBuilder().getBuilder();
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      public ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder getScopeOrBuilder() {
        if (scopeBuilder_ != null) {
          return scopeBuilder_.getMessageOrBuilder();
        } else {
          return scope_ == null ?
              ProofScopeRequestOuterClass.ProofScopeRequest.getDefaultInstance() : scope_;
        }
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofScopeRequest scope = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProofScopeRequestOuterClass.ProofScopeRequest, ProofScopeRequestOuterClass.ProofScopeRequest.Builder, ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder>
          getScopeFieldBuilder() {
        if (scopeBuilder_ == null) {
          scopeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProofScopeRequestOuterClass.ProofScopeRequest, ProofScopeRequestOuterClass.ProofScopeRequest.Builder, ProofScopeRequestOuterClass.ProofScopeRequestOrBuilder>(
                  getScope(),
                  getParentForChildren(),
                  isClean());
          scope_ = null;
        }
        return scopeBuilder_;
      }

      private com.google.protobuf.MapField<
          String, com.google.protobuf.Value> context_;
      private com.google.protobuf.MapField<String, com.google.protobuf.Value>
          internalGetContext() {
        if (context_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ContextDefaultEntryHolder.defaultEntry);
        }
        return context_;
      }
      private com.google.protobuf.MapField<String, com.google.protobuf.Value>
          internalGetMutableContext() {
        if (context_ == null) {
          context_ = com.google.protobuf.MapField.newMapField(
              ContextDefaultEntryHolder.defaultEntry);
        }
        if (!context_.isMutable()) {
          context_ = context_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return context_;
      }
      public int getContextCount() {
        return internalGetContext().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      @Override
      public boolean containsContext(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetContext().getMap().containsKey(key);
      }
      /**
       * Use {@link #getContextMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Value> getContext() {
        return getContextMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      @Override
      public java.util.Map<String, com.google.protobuf.Value> getContextMap() {
        return internalGetContext().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      @Override
      public /* nullable */
com.google.protobuf.Value getContextOrDefault(
          String key,
          /* nullable */
com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, com.google.protobuf.Value> map =
            internalGetContext().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      @Override
      public com.google.protobuf.Value getContextOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<String, com.google.protobuf.Value> map =
            internalGetContext().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearContext() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableContext().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      public Builder removeContext(
          String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableContext().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, com.google.protobuf.Value>
          getMutableContext() {
        bitField0_ |= 0x00000002;
        return internalGetMutableContext().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      public Builder putContext(
          String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableContext().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; context = 2;</code>
       */
      public Builder putAllContext(
          java.util.Map<String, com.google.protobuf.Value> values) {
        internalGetMutableContext().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      private ProofQueryParamEntity queryParam_;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProofQueryParamEntity, ProofQueryParamEntity.Builder, ProofQueryParamEntityOrBuilder> queryParamBuilder_;
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       * @return Whether the queryParam field is set.
       */
      public boolean hasQueryParam() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       * @return The queryParam.
       */
      public ProofQueryParamEntity getQueryParam() {
        if (queryParamBuilder_ == null) {
          return queryParam_ == null ? ProofQueryParamEntity.getDefaultInstance() : queryParam_;
        } else {
          return queryParamBuilder_.getMessage();
        }
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public Builder setQueryParam(ProofQueryParamEntity value) {
        if (queryParamBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          queryParam_ = value;
        } else {
          queryParamBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public Builder setQueryParam(
          ProofQueryParamEntity.Builder builderForValue) {
        if (queryParamBuilder_ == null) {
          queryParam_ = builderForValue.build();
        } else {
          queryParamBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public Builder mergeQueryParam(ProofQueryParamEntity value) {
        if (queryParamBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            queryParam_ != null &&
            queryParam_ != ProofQueryParamEntity.getDefaultInstance()) {
            getQueryParamBuilder().mergeFrom(value);
          } else {
            queryParam_ = value;
          }
        } else {
          queryParamBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public Builder clearQueryParam() {
        bitField0_ = (bitField0_ & ~0x00000004);
        queryParam_ = null;
        if (queryParamBuilder_ != null) {
          queryParamBuilder_.dispose();
          queryParamBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public ProofQueryParamEntity.Builder getQueryParamBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getQueryParamFieldBuilder().getBuilder();
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      public ProofQueryParamEntityOrBuilder getQueryParamOrBuilder() {
        if (queryParamBuilder_ != null) {
          return queryParamBuilder_.getMessageOrBuilder();
        } else {
          return queryParam_ == null ?
              ProofQueryParamEntity.getDefaultInstance() : queryParam_;
        }
      }
      /**
       * <code>.technology.polygon.polygonid_protobuf.ProofRequestEntity.ProofQueryParamEntity queryParam = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProofQueryParamEntity, ProofQueryParamEntity.Builder, ProofQueryParamEntityOrBuilder>
          getQueryParamFieldBuilder() {
        if (queryParamBuilder_ == null) {
          queryParamBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProofQueryParamEntity, ProofQueryParamEntity.Builder, ProofQueryParamEntityOrBuilder>(
                  getQueryParam(),
                  getParentForChildren(),
                  isClean());
          queryParam_ = null;
        }
        return queryParamBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:technology.polygon.polygonid_protobuf.ProofRequestEntity)
    }

    // @@protoc_insertion_point(class_scope:technology.polygon.polygonid_protobuf.ProofRequestEntity)
    private static final ProofRequestEntity DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProofRequestEntity();
    }

    public static ProofRequestEntity getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProofRequestEntity>
        PARSER = new com.google.protobuf.AbstractParser<ProofRequestEntity>() {
      @Override
      public ProofRequestEntity parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ProofRequestEntity> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProofRequestEntity> getParserForType() {
      return PARSER;
    }

    @Override
    public ProofRequestEntity getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\032proof_request_entity.proto\022%technology" +
      ".polygon.polygonid_protobuf\032\034google/prot" +
      "obuf/struct.proto\032\031proof_scope_request.p" +
      "roto\"\255\003\n\022ProofRequestEntity\022G\n\005scope\030\001 \001" +
      "(\01328.technology.polygon.polygonid_protob" +
      "uf.ProofScopeRequest\022W\n\007context\030\002 \003(\0132F." +
      "technology.polygon.polygonid_protobuf.Pr" +
      "oofRequestEntity.ContextEntry\022c\n\nqueryPa" +
      "ram\030\003 \001(\0132O.technology.polygon.polygonid" +
      "_protobuf.ProofRequestEntity.ProofQueryP" +
      "aramEntity\032F\n\014ContextEntry\022\013\n\003key\030\001 \001(\t\022" +
      "%\n\005value\030\002 \001(\0132\026.google.protobuf.Value:\002" +
      "8\001\032H\n\025ProofQueryParamEntity\022\r\n\005field\030\001 \001" +
      "(\t\022\016\n\006values\030\002 \003(\005\022\020\n\010operator\030\003 \001(\005b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          ProofScopeRequestOuterClass.getDescriptor(),
        });
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor,
        new String[] { "Scope", "Context", "QueryParam", });
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_descriptor =
      internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor.getNestedTypes().get(0);
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ContextEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor =
      internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_descriptor.getNestedTypes().get(1);
    internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_technology_polygon_polygonid_protobuf_ProofRequestEntity_ProofQueryParamEntity_descriptor,
        new String[] { "Field", "Values", "Operator", });
    com.google.protobuf.StructProto.getDescriptor();
    ProofScopeRequestOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
