{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.1.aar",
          "url": "path_provider_android_debug-1.0.1.aar",
          "size": 12982,
          "sha512": "8a20d025fa8bac6549e4f193c3d8eabf66d02a40ae16e7aec31e09a5227c75ff443a685ac101bac8638aba33b3fe74ed3371888148d58b370d21a15a60be5f13",
          "sha256": "5acf418f0fba4bdf397ee73efb653e66eca0cacdacf86c36fa131b96e6bbce99",
          "sha1": "94c40bfb31f0dbfae67d972128e639f9c8d127f3",
          "md5": "8c45fe5c2d886d5978254238eef8ea22"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-0f359063c487ee70787e58b4b011cbb3c2f53fd6"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.1.aar",
          "url": "path_provider_android_debug-1.0.1.aar",
          "size": 12982,
          "sha512": "8a20d025fa8bac6549e4f193c3d8eabf66d02a40ae16e7aec31e09a5227c75ff443a685ac101bac8638aba33b3fe74ed3371888148d58b370d21a15a60be5f13",
          "sha256": "5acf418f0fba4bdf397ee73efb653e66eca0cacdacf86c36fa131b96e6bbce99",
          "sha1": "94c40bfb31f0dbfae67d972128e639f9c8d127f3",
          "md5": "8c45fe5c2d886d5978254238eef8ea22"
        }
      ]
    }
  ]
}
